### ISSUE TITLE
Could you clarify the in the README if it acts on the host or the container please?

### ISSUE THREAD

**Issue by vitaprimo** [iv-org/smart-ipv6-rotator#17]
I was just about to deploy when I realized this might be changing the server's network, I'm not sure though.

I modified my compose to specify specific **macvlan subnet and addresses** so I can tell the traffic apart from the server's which itself isn't allowed to connect to the Internet. 
```
# invidious service
    networks:
      z0a00:
        ipv4_address: 10.10.0.48
# db service:
    networks:
      z0a00:
        ipv4_address: 10.10.0.49
# network defs:
networks:
  z0a00:
    external: true

```

I adjusted the last part as:
```
networks:
  z0a00:
    external: true
    enable_ipv6: true
      ipam:
        config:
          - subnet: 2001:0DB9::/112
            gateway: 2001:0DB9::1
```
I assumed the address is just a placeholder given the range, but otherwise I don't know if that's correct. I've set up macvlan on compose only once before…in this same config. :/

The original code was:
```
networks:
  default:
    enable_ipv6: true
      ipam:
        config:
          - subnet: 2001:0DB9::/112
            gateway: 2001:0DB9::1
```
If I remember correctly — it's been a while since I switched it and I normally don't use compose if I can avoid it — that's (`default:`) when it shares the network with the host, ain't it? Therefore it would be changing the host's network, not the container's network, it seems. The host has about six other networks, all dual stack; this is the least preferred. It will get very messy if it does.

Thanks!
